### ISSUE TITLE
Share code

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/CudaText-SQLTools#6]
It would be very good if MAIN part of SqlTools- shared - as .py file- between ST3 and Cud.
So it's easy for u to update Cud vers.
(this part must not import "cudatext"!!)

**Comment by mtxr** [comment]
Today I started to create a SQLTools API to share between the plugins of Sublime and Cuda.
Sublime has an dependency manger for requiring contents of the package and I'm thinking about using it instead of update plugin manually every time.

Does cuda has something like that or should I code it for auto updating?

**Comment by Alexey-T** [comment]
Cud has this: u create 2nd zip file, and it also installs folder to "py". this folder is not plugin but Py module. but... not good. not good for users. good: make one single zip

**Comment by Alexey-T** [comment]
Matheus,
You wanted to use API (shared) in this plugin. but I dont see API here yet. no folder like in ST3 code.

**Comment by mtxr** [comment]
Yes, it's in development

**Comment by mtxr** [comment]
closed on last commit
